# Generated by Django 5.0.1 on 2024-02-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='room_name',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
